name: Code Quality and Lint
on: [push, pull_request]

jobs:
  lint:
    name: Python Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Linters
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "sapcommissions tests"
          use-mypy: false
          use-pycodestyle: false
          use-pylint: false
          use-flake8: true
          use-black: true
          use-isort: true
          extra-flake8-options: "--max-line-length 88 --extend-ignore E203"
          extra-black-options: "--line-length 88"
          extra-isort-options: "--line-length 88 --profile black"
