name: Code Quality and Lint
on: [pull_request]

jobs:
  lint:
    name: Python Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Linters
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "sapcommissions tests"
          use-mypy: false
          use-pycodestyle: true
          use-pylint: false
          extra-pylint-options: "--rcfile=pyproject.toml"
          use-flake8: true
          extra-flake8-options: "--config=tox.ini"
          use-black: true
          use-isort: true
